# .github/workflows/pages.yml
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: # enables manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # required to deploy Pages
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
